# Cloudflare Workers Configuration for Marketing Strategy API
name = "glow-api-lingering-queen-74b7"
main = "workers/worker.js" 
compatibility_date = "2025-01-01"

# KV namespace for rate limiting (will be added later)
# [[kv_namespaces]]
# binding = "RATE_LIMIT_KV"
# preview_id = "rate_limit_preview"
# id = "rate_limit_production"

# Environment variables
[vars]
ENVIRONMENT = "production"

# Custom domain configured via Cloudflare Dashboard