# Cloudflare Workers Configuration for Marketing Strategy API

# Default configuration points to development worker (safe default)
name = "glow-api-dev-lingering-queen-74b7"
main = "workers/worker.js" 
compatibility_date = "2025-01-01"

# Default environment variables for development
[vars]
ENVIRONMENT = "development"

# Development environment (default, safe)
[env.dev]
name = "glow-api-dev-lingering-queen-74b7"
[env.dev.vars]
ENVIRONMENT = "development"

# Production environment (explicit flag required)
[env.production] 
name = "glow-api-lingering-queen-74b7"
[env.production.vars]
ENVIRONMENT = "production"

# KV namespace for rate limiting (will be added later)
# [[kv_namespaces]]
# binding = "RATE_LIMIT_KV"
# preview_id = "rate_limit_preview"
# id = "rate_limit_production"

# Custom domain configured via Cloudflare Dashboard for production only